[[DSSP]]
arch = "aarch64"
git-tree-sha1 = "2f440a9045ca406126133aff2a0e5bda04ece447"
os = "macos"

    [[DSSP.download]]
    sha256 = "7771e7af022b2cc639b8c7cf4949a979a08c84a3f5f7294a75a660db2d2b4d13"
    url = "https://github.com/JuliaBinaryWrappers/DSSP_jll.jl/releases/download/DSSP-v4.4.0+0/DSSP.v4.4.0.aarch64-apple-darwin.tar.gz"
[[DSSP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eff93f7196ab76b68f9f8db850ab4f7d7166dd61"
libc = "glibc"
os = "linux"

    [[DSSP.download]]
    sha256 = "9f83c094cad39e0934a0d33eb7e2dd75d341c3bd8d19dfb0a1466f8b2cd9b566"
    url = "https://github.com/JuliaBinaryWrappers/DSSP_jll.jl/releases/download/DSSP-v4.4.0+0/DSSP.v4.4.0.aarch64-linux-gnu-cxx03.tar.gz"
[[DSSP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6b73d3b2a9670b9ab227f699d3b7c2213134b28"
libc = "glibc"
os = "linux"

    [[DSSP.download]]
    sha256 = "b77071af6bcccfe6feadec2e0a0fe7390fc9920d387077cc277146504813ac89"
    url = "https://github.com/JuliaBinaryWrappers/DSSP_jll.jl/releases/download/DSSP-v4.4.0+0/DSSP.v4.4.0.aarch64-linux-gnu-cxx11.tar.gz"
[[DSSP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6259982880e4cba269aaf5d98adc30a7dd7a706c"
libc = "musl"
os = "linux"

    [[DSSP.download]]
    sha256 = "a50cc0cb16a9f924b6460bf9fdfd2009f8dcb5448532dafb737398cbd83bd055"
    url = "https://github.com/JuliaBinaryWrappers/DSSP_jll.jl/releases/download/DSSP-v4.4.0+0/DSSP.v4.4.0.aarch64-linux-musl-cxx03.tar.gz"
[[DSSP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e7b62ddd253ff217e290cb93dd530ecf2d0aca1"
libc = "musl"
os = "linux"

    [[DSSP.download]]
    sha256 = "4f3412413381c968b2aa6edebb0eb3c61e25a06a177e5193890c681fd00a84dd"
    url = "https://github.com/JuliaBinaryWrappers/DSSP_jll.jl/releases/download/DSSP-v4.4.0+0/DSSP.v4.4.0.aarch64-linux-musl-cxx11.tar.gz"
[[DSSP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8a5960dd5344d88e99547fafacf62348a3424501"
libc = "glibc"
os = "linux"

    [[DSSP.download]]
    sha256 = "64ab121248d1d123ac2dbba6fc32e428ea281c823f6172aacfbc93e518387e83"
    url = "https://github.com/JuliaBinaryWrappers/DSSP_jll.jl/releases/download/DSSP-v4.4.0+0/DSSP.v4.4.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[DSSP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd0391a30585aba5d28bde2a891ee4a764501f4f"
libc = "glibc"
os = "linux"

    [[DSSP.download]]
    sha256 = "b8bfb89a347d1ebc1dfe990d78a582c78a4a3c716cf3dc133b3353c20b866892"
    url = "https://github.com/JuliaBinaryWrappers/DSSP_jll.jl/releases/download/DSSP-v4.4.0+0/DSSP.v4.4.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[DSSP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "209afbe63e1c93a9858a1f64acdcf95010cac81b"
libc = "musl"
os = "linux"

    [[DSSP.download]]
    sha256 = "37ec4ad7fc5f50bba2a40af50f183edf3955eb1bbfa01ee58e17eb0317837ca5"
    url = "https://github.com/JuliaBinaryWrappers/DSSP_jll.jl/releases/download/DSSP-v4.4.0+0/DSSP.v4.4.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[DSSP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "acf9d666584a744ae44f471997cf83b6ea8a3644"
libc = "musl"
os = "linux"

    [[DSSP.download]]
    sha256 = "f3e66116e70093f8c2d32215a3c616903d3427e551c274f1ace9a52d8c62d711"
    url = "https://github.com/JuliaBinaryWrappers/DSSP_jll.jl/releases/download/DSSP-v4.4.0+0/DSSP.v4.4.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[DSSP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "246ae3e740aefe85ebe84db1d52320e9e29fd4dd"
libc = "glibc"
os = "linux"

    [[DSSP.download]]
    sha256 = "cf05d1368af1bc4371d72ad919e8c1b122ca38f9770a2027b6314f4414c7c9ce"
    url = "https://github.com/JuliaBinaryWrappers/DSSP_jll.jl/releases/download/DSSP-v4.4.0+0/DSSP.v4.4.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[DSSP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "330cf7a3c2ec9de40500123f07436b7a33150519"
libc = "glibc"
os = "linux"

    [[DSSP.download]]
    sha256 = "b010896553befde3147ee890d558d8dc238ee8b5e19ba92a8a703ec09ba72142"
    url = "https://github.com/JuliaBinaryWrappers/DSSP_jll.jl/releases/download/DSSP-v4.4.0+0/DSSP.v4.4.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[DSSP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de0485054995061fe70aab50a229029aed101d8a"
libc = "musl"
os = "linux"

    [[DSSP.download]]
    sha256 = "45f87bcb1b62548bb0c09469a49beea484921eebb13737e19fbb19c67e27afa2"
    url = "https://github.com/JuliaBinaryWrappers/DSSP_jll.jl/releases/download/DSSP-v4.4.0+0/DSSP.v4.4.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[DSSP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e59259d54b35323b1eb0513eb19d4aaf6e292757"
libc = "musl"
os = "linux"

    [[DSSP.download]]
    sha256 = "d023a77d76c3940a35acf467afe958befb16cbdc22b6fcb142f83a6d83a4ff59"
    url = "https://github.com/JuliaBinaryWrappers/DSSP_jll.jl/releases/download/DSSP-v4.4.0+0/DSSP.v4.4.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[DSSP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1c9208b4efa22c18a05faebf54e0df42e84b9aa2"
libc = "glibc"
os = "linux"

    [[DSSP.download]]
    sha256 = "f40a4e4b10febdbcdf150c854e2a0cc6eb7403f4b703213f35c287a24cf4fcb7"
    url = "https://github.com/JuliaBinaryWrappers/DSSP_jll.jl/releases/download/DSSP-v4.4.0+0/DSSP.v4.4.0.i686-linux-gnu-cxx03.tar.gz"
[[DSSP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f599afef95e628d1a8c1d4b5733dd646411b6f42"
libc = "glibc"
os = "linux"

    [[DSSP.download]]
    sha256 = "3ea0caa22a137fa52b65f607439c408e69c79051ad402d7aee768307d332e35d"
    url = "https://github.com/JuliaBinaryWrappers/DSSP_jll.jl/releases/download/DSSP-v4.4.0+0/DSSP.v4.4.0.i686-linux-gnu-cxx11.tar.gz"
[[DSSP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cc0e46c30f2ffe8b6109fd226c93122c74ea5798"
libc = "musl"
os = "linux"

    [[DSSP.download]]
    sha256 = "b5cfd28b74eba2b4e26c15728bb08d99412a8ca83516003712ca9fc37d0cb382"
    url = "https://github.com/JuliaBinaryWrappers/DSSP_jll.jl/releases/download/DSSP-v4.4.0+0/DSSP.v4.4.0.i686-linux-musl-cxx03.tar.gz"
[[DSSP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12a9267947fad3e11bfa23e6addccb06eaafc5bd"
libc = "musl"
os = "linux"

    [[DSSP.download]]
    sha256 = "3c341b04daa5734c2f6280f4787a513ea6d1a0d1cad8344708db3623ee197a6e"
    url = "https://github.com/JuliaBinaryWrappers/DSSP_jll.jl/releases/download/DSSP-v4.4.0+0/DSSP.v4.4.0.i686-linux-musl-cxx11.tar.gz"
[[DSSP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b79d0dfcf58dff31f34bf51ba6b275f8b4540889"
os = "windows"

    [[DSSP.download]]
    sha256 = "abaa176aeebc77319a49b8975c92fbcbe6c8e646541525113dcb17082af84686"
    url = "https://github.com/JuliaBinaryWrappers/DSSP_jll.jl/releases/download/DSSP-v4.4.0+0/DSSP.v4.4.0.i686-w64-mingw32-cxx03.tar.gz"
[[DSSP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a8607fb9cad61aff6161027a9ce02c69b4cb07e5"
os = "windows"

    [[DSSP.download]]
    sha256 = "28ef0df81814af2c305ae0a204e57638a033c7c7f0b5f8a8756d2d96f4d0ddef"
    url = "https://github.com/JuliaBinaryWrappers/DSSP_jll.jl/releases/download/DSSP-v4.4.0+0/DSSP.v4.4.0.i686-w64-mingw32-cxx11.tar.gz"
[[DSSP]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "62e3699a01b41448b23a9393327718e091d510ea"
libc = "glibc"
os = "linux"

    [[DSSP.download]]
    sha256 = "a6e877df626413c8b29a0f58f7a8e536e97d6316a56d3e0a83d9f0f696e546a3"
    url = "https://github.com/JuliaBinaryWrappers/DSSP_jll.jl/releases/download/DSSP-v4.4.0+0/DSSP.v4.4.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[DSSP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "48b6f8e31f4e17c61bce7ec187329bd5637bc633"
libc = "glibc"
os = "linux"

    [[DSSP.download]]
    sha256 = "7ea4ba00f59a58d2f06f939aec8abebc520f155d195cde4cc78d1e3a17ded7d5"
    url = "https://github.com/JuliaBinaryWrappers/DSSP_jll.jl/releases/download/DSSP-v4.4.0+0/DSSP.v4.4.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[DSSP]]
arch = "x86_64"
git-tree-sha1 = "d9b8559a7f9211809813ca401e03478a348b6a82"
os = "macos"

    [[DSSP.download]]
    sha256 = "fe062fdedec2fea120acaff7a66ac2ba4740706c6a556c0a98ca795dd899cfc3"
    url = "https://github.com/JuliaBinaryWrappers/DSSP_jll.jl/releases/download/DSSP-v4.4.0+0/DSSP.v4.4.0.x86_64-apple-darwin.tar.gz"
[[DSSP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "902b29e75ec1126f967c3da59f708a056878f7fa"
libc = "glibc"
os = "linux"

    [[DSSP.download]]
    sha256 = "db3d0941d1f8d66b2176f79434a7285152084300fe351bbe131ec679731b0581"
    url = "https://github.com/JuliaBinaryWrappers/DSSP_jll.jl/releases/download/DSSP-v4.4.0+0/DSSP.v4.4.0.x86_64-linux-gnu-cxx03.tar.gz"
[[DSSP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fa3583fe41a84ab42c11e7d2aa0f2739d15da645"
libc = "glibc"
os = "linux"

    [[DSSP.download]]
    sha256 = "0c786c8645994f1057a06276a940b6b34d078681d186cd8460c8282ddb063345"
    url = "https://github.com/JuliaBinaryWrappers/DSSP_jll.jl/releases/download/DSSP-v4.4.0+0/DSSP.v4.4.0.x86_64-linux-gnu-cxx11.tar.gz"
[[DSSP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d68a91b07be340075c21a95f4dc1b55e6a159755"
libc = "musl"
os = "linux"

    [[DSSP.download]]
    sha256 = "28a535c37ca369b88768a0004b97445fb59f4707228e4a44e4e0f8d26468dfc1"
    url = "https://github.com/JuliaBinaryWrappers/DSSP_jll.jl/releases/download/DSSP-v4.4.0+0/DSSP.v4.4.0.x86_64-linux-musl-cxx03.tar.gz"
[[DSSP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0ea5e80b7f8a054defeae05865ebd91340cae70d"
libc = "musl"
os = "linux"

    [[DSSP.download]]
    sha256 = "853861fc7273f8246a9e82d6ab65fd2bcfcd08f2d8a5ac6bec1b713c312101df"
    url = "https://github.com/JuliaBinaryWrappers/DSSP_jll.jl/releases/download/DSSP-v4.4.0+0/DSSP.v4.4.0.x86_64-linux-musl-cxx11.tar.gz"
[[DSSP]]
arch = "x86_64"
git-tree-sha1 = "8f562b5c17a6ce3b45645cf5478351556d02cf4d"
os = "freebsd"

    [[DSSP.download]]
    sha256 = "a34d9af90d927b9d40abee1620c58c153633ecb721948c9dbb2f0e3fb09743be"
    url = "https://github.com/JuliaBinaryWrappers/DSSP_jll.jl/releases/download/DSSP-v4.4.0+0/DSSP.v4.4.0.x86_64-unknown-freebsd.tar.gz"
[[DSSP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9fe3a0cf961903eeba4eb3db114e550d28a1742d"
os = "windows"

    [[DSSP.download]]
    sha256 = "12cb98a4283ba6e70dfaef385e2c3b35ea459577363f6d82805ed04f135e2ba5"
    url = "https://github.com/JuliaBinaryWrappers/DSSP_jll.jl/releases/download/DSSP-v4.4.0+0/DSSP.v4.4.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[DSSP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "350c7eb1cfc952ee9c2c5e9879f8741fbe4e2492"
os = "windows"

    [[DSSP.download]]
    sha256 = "9928e7b86b054d2425c284eb0196b82f8e601464bc762d7151670ad2cad36751"
    url = "https://github.com/JuliaBinaryWrappers/DSSP_jll.jl/releases/download/DSSP-v4.4.0+0/DSSP.v4.4.0.x86_64-w64-mingw32-cxx11.tar.gz"
