# Autogenerated wrapper script for DSSP_jll for powerpc64le-linux-gnu-cxx11
export mkdssp

using Zlib_jll
JLLWrappers.@generate_wrapper_header("DSSP")
JLLWrappers.@declare_executable_product(mkdssp)
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_executable_product(
        mkdssp,
        "bin/mkdssp",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
